# Generated by Django 6.0.4 on 2026-04-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='company',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='lead',
            name='service',
            field=models.CharField(blank=True, choices=[('office', 'Office Cleaning'), ('clinic', 'Clinic / Medical'), ('warehouse', 'Warehouse / Industrial'), ('retail', 'Retail / Commercial'), ('other', 'Other')], max_length=20),
        ),
    ]
