# Generated by Django 6.0.4 on 2026-06-01 16:39

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_lead_company_lead_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketimage',
            name='image',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='tickets/'),
        ),
    ]
